server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: catalogRoute
            uri: lb://catalog/
            predicates:
              - Path=/catalog/**